### ISSUE TITLE
No albums, photos, upload

### ISSUE THREAD

**Issue by ghost** [djmonta/zenphoto-swift#1]
I have installed the app on my iPad (iPad2 iOS 8.3) and followed the instructions on http://zenphoto-app.tumblr.com/ but nothing shows up in the app.

The app has been configured with my Site URL (internal) and login information but i cannot see/add albums, photos.

Zenphoto version is 1.4.8

Please help

**Comment by ghost** [comment]
Sorry, I used the wrong folder (zp-extensions)

**Comment by djmonta** [comment]
Sorry for inconvenience.

Adding album and photos function for iPad is seem to be buggy, I will fix it next release.
